source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme

export ZSH="$HOME/.oh-my-zsh"

zstyle ':omz:update' mode auto
zstyle ':completion:*' rehash true

ENABLE_CORRECTION="true"
HIST_STAMPS="yyyy-mm-dd"

plugins=( git )

source $ZSH/oh-my-zsh.sh

export EDITOR='nvim'

alias yolo='sudo pacman -Sy --noconfirm archlinux-keyring && yay -Syu --noconfirm'
alias pwgen='pwgen -s -1 -y'
alias vim='nvim'
alias testwm='Xephyr :5 & sleep 1 ; DISPLAY=:5 awesome'

alias cfg='cd ~/dotfiles/config'
alias dotf='cd ~/dotfiles'

export GPG_TTY=$(tty)

[[ ! -f ~/dotfiles/config/zsh/p10k.zsh ]] || source ~/dotfiles/config/zsh/p10k.zsh

if [ -z "$DISPLAY" ] && [ "$XDG_VTNR" = 1 ]; then
  startx
fi

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/usr/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/usr/etc/profile.d/conda.sh" ]; then
        . "/usr/etc/profile.d/conda.sh"
    else
        export PATH="/usr/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

