#!/usr/bin/env python3
import os
import sys
import shutil

blacklist = [
    "_",
    "OLDPWD",
    "PWD",
    "SHLVL",
    "TERM",
]

envdir = os.path.join("/run", str(os.getuid()), "env")

if os.path.exists(envdir):
    shutil.rmtree(envdir)

os.makedirs(envdir)

for name, val in filter(lambda var: var[0] not in blacklist,
                        os.environ.items()):
    with open(os.path.join(envdir, name), "w") as file:
        file.write(val)
